# Generated by Django 3.0.3 on 2020-08-28 16:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 28, 22, 23, 24, 633359))),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('choice1', models.CharField(default='', max_length=100)),
                ('choice2', models.CharField(default='', max_length=100)),
                ('choice3', models.CharField(default='', max_length=100)),
                ('choice4', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 28, 22, 23, 24, 633359))),
                ('answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=4)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='teacher_app.Paper')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
