# Generated by Django 3.0.3 on 2020-08-29 15:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 29, 21, 3, 8, 554433))),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 29, 21, 3, 8, 556186))),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=4)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='teacher_app.Paper')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
