# Generated by Django 3.0.3 on 2020-08-29 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 21, 7, 35, 905856)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 21, 7, 35, 905856)),
        ),
    ]
