# Generated by Django 3.0.3 on 2020-08-30 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_auto_20200829_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 35, 32, 208583)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 35, 32, 209581)),
        ),
    ]
