# Generated by Django 3.0.3 on 2020-08-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_papers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papers',
            new_name='Paper',
        ),
    ]
