# Generated by Django 3.0.3 on 2020-08-30 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_auto_20200830_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 36, 40, 326318)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 36, 40, 327315)),
        ),
    ]
