# Generated by Django 3.0.3 on 2020-08-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_auto_20200828_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='author',
            new_name='user',
        ),
    ]
