# Generated by Django 3.0.3 on 2020-08-30 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_auto_20200830_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 37, 47, 233968)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 37, 47, 233968)),
        ),
    ]
