# Generated by Django 3.0.3 on 2020-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0005_auto_20200828_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
