# Generated by Django 3.0.3 on 2020-08-31 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0007_auto_20200831_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 21, 30, 47, 356422)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 21, 30, 47, 356422)),
        ),
    ]
