# Generated by Django 3.0.3 on 2020-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionclone',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionclone',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionclone',
            name='answer',
            field=models.CharField(default='E', max_length=10),
        ),
    ]
