# Generated by Django 3.0.3 on 2020-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperclone',
            options={'ordering': ['-result']},
        ),
        migrations.AddField(
            model_name='paperclone',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
